services:
  spinoza-db:
    image: postgres:16-alpine
    container_name: spinoza-db
    environment:
      POSTGRES_DB: spinoza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5464:5432"
    volumes:
      - spinoza_db_data:/var/lib/postgresql/data

  spinoza:
    build:
      context: .
      dockerfile: spinoza-notify/Dockerfile
    container_name: spinoza
    ports:
      - "5005:5005"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5005
      ConnectionStrings__DefaultConnection: Host=spinoza-db;Port=5432;Database=spinoza;Username=postgres;Password=postgres
    depends_on:
      - spinoza-db

volumes:
  spinoza_db_data:
